import type { Metadata } from 'next'
import { getServerSession } from '@/actions/auth.actions'
import { adminDb } from '@/lib/firebase/admin'

export const metadata: Metadata = {
  title: 'Demo Page',
}

export default async function DemoPage() {
  const session = await getServerSession()
  const profileSnap = session ? await adminDb.collection('users').doc(session.uid).get() : null

  const displayName = profileSnap?.exists
    ? (profileSnap.data()?.displayName as string | null)
    : null
  const greetingName = displayName ?? session?.email ?? null

  return (
    //page output - this is a demo, hence only placeholders are coded
    <div className="space-y-6">
    {/* Header Title */}
    <div>   
      <h1 className="text-2xl font-bold tracking-tight">Demo Page</h1>
    </div>

    {/* Body code, outlined the div containers to demo and showcase the structure of the page. 
    Text in each container is to explain what each section would be for in a very general sense */}
    <div className="rounded-xl border bg-zinc-800 p-6 shadow-sm">
      <h2 className="text-lg font-semibold">Pipeline Output</h2>
      <p className="mt-1 text-sm text-zinc-500">
        The results generated by the pipeline will be displayed here.
      </p>

      <div className="mt-6 flex min-h-48 items-center justify-center rounded-lg border border-dashed bg-zinc-300">
        <p className="text-sm text-zinc-400">
          Awaiting pipeline output...
        </p>
      </div>
    </div>
  </div>
  )
}

